name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x", "18.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 🏗 Setup repo
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: pnpm build
