name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'tonightpass/kitchen'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 🏗 Setup repo
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
          commit: "🔖 release version"
          title: "🔖 release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
